server:
    port: 58080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yutask?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
        hikari:
            maximum-pool-size: 30
            keepalive-time: 30000
            connection-timeout: 30000
    servlet:
        multipart:
            # 单个文件最大大小
            max-file-size: 500MB
            # 单次请求总文件大小
            max-request-size: 500MB
            # 可选：临时文件存储路径
            location: tmp/upload
            # 可选：延迟解析
            resolve-lazily: false
mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
qiniu:
    access-key: QTQ0T2Q6FaDGTXn1K8-2iLNR4X4BVoeik4DVeKhJ
    secret-key: 4z_c6h8KVYAcjqUtombnlzQQ8CLKrqp8GAKwoUMf
    bucket: oss-qiniu-partialy
    domain: //partialy.qiniu.partialy.cn
    cdn-domain: //cdn-partialy-qiniu.partialy.cn
    upload-url: https://upload.qiniup.com
aes:
    key: 1234567890abcdef1234567890abcdef
jwt:
    secret: xianyuSecretKeyForJwtToken
    expiration: 604800 # 7 days in seconds

# 文件上传配置
file:
    upload:
        path: upload/