"use strict";var E=Object.defineProperty;var M=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var N=(e,t)=>{for(var l in t)E(e,l,{get:t[l],enumerable:!0})},H=(e,t,l,s)=>{if(t&&typeof t=="object"||typeof t=="function")for(let a of P(t))!S.call(e,a)&&a!==l&&E(e,a,{get:()=>t[a],enumerable:!(s=M(t,a))||s.enumerable});return e};var I=e=>H(E({},"__esModule",{value:!0}),e);var F={};N(F,{datePicker:()=>w,default:()=>O});module.exports=I(F);var x="datepicker-wrapper",L="datepicker-injected-styles",_=["\u65E5","\u4E00","\u4E8C","\u4E09","\u56DB","\u4E94","\u516D"],q=`
.datepicker-overlay{position:fixed;inset:0;z-index:10003;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.45);opacity:0;visibility:hidden;transition:opacity .2s ease,visibility .2s ease}
.datepicker-overlay.datepicker-visible{opacity:1;visibility:visible}
.datepicker-box{margin:24px;padding:12px;background:#fff;border-radius:8px;box-shadow:0 6px 24px rgba(0,0,0,.15);border:1px solid #e8e8e8}
.datepicker-calendar{min-width:280px}
.datepicker-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}
.datepicker-title{display:flex;align-items:center;gap:2px;font-size:14px;font-weight:600;color:#333}
.datepicker-title-part{padding:4px 6px;border:none;background:transparent;border-radius:4px;font-size:inherit;font-weight:inherit;color:inherit;cursor:pointer}
.datepicker-title-part:hover{background:#e6f7ff;color:#1890ff}
.datepicker-panel{min-width:280px}
.datepicker-panel-title{padding:4px 8px;border:none;background:transparent;border-radius:4px;font-size:14px;font-weight:600;color:#333;cursor:pointer}
.datepicker-panel-title:hover{background:#e6f7ff;color:#1890ff}
.datepicker-month-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}
.datepicker-month-cell{padding:10px;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-month-cell:hover{background:#e6f7ff;color:#1890ff}
.datepicker-year-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}
.datepicker-year-cell{padding:10px;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-year-cell:hover{background:#e6f7ff;color:#1890ff}
.datepicker-nav{width:28px;height:28px;padding:0;border:none;background:transparent;border-radius:6px;font-size:18px;line-height:1;color:#666;cursor:pointer;display:flex;align-items:center;justify-content:center}
.datepicker-nav:hover{background:#f5f5f5;color:#333}
.datepicker-weekdays{display:grid;grid-template-columns:repeat(7,1fr);gap:2px;margin-bottom:8px}
.datepicker-weekday{text-align:center;font-size:12px;color:#999}
.datepicker-days{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}
.datepicker-day{width:36px;height:36px;padding:0;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-day:hover{background:#e6f7ff;color:#1890ff}
.datepicker-day-other{color:#bfbfbf}
.datepicker-day-today{background:#e6f7ff;color:#1890ff;font-weight:600}
.datepicker-day.datepicker-day-today:hover{background:#bae7ff}
`;function z(){if(typeof document>"u"||document.getElementById(L))return;let e=document.createElement("style");e.id=L,e.textContent=q,document.head.appendChild(e)}var $=["1\u6708","2\u6708","3\u6708","4\u6708","5\u6708","6\u6708","7\u6708","8\u6708","9\u6708","10\u6708","11\u6708","12\u6708"],b=12;function A(e){let t=e.getFullYear(),l=String(e.getMonth()+1).padStart(2,"0"),s=String(e.getDate()).padStart(2,"0");return`${t}-${l}-${s}`}function Y(e){if(!e)return null;let t=new Date(e);return isNaN(t.getTime())?null:t}function j(e,t){let l=new Date(e,t,1),s=new Date(e,t+1,0),a=l.getDay(),p=s.getDate(),c=[],n=new Date;n.setHours(0,0,0,0);for(let i=0;i<a;i++){let d=new Date(e,t,1-(a-i));c.push({date:d,isCurrent:!1,isToday:d.getTime()===n.getTime()})}for(let i=1;i<=p;i++){let d=new Date(e,t,i);c.push({date:d,isCurrent:!0,isToday:d.getTime()===n.getTime()})}let r=42-c.length;for(let i=1;i<=r;i++){let d=new Date(e,t+1,i);c.push({date:d,isCurrent:!1,isToday:d.getTime()===n.getTime()})}return c}function R(e,t,l,s,a,p){let c=document.createElement("div");c.className="datepicker-calendar";let n=document.createElement("div");n.className="datepicker-header",n.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u6708">\u2039</button>
    <span class="datepicker-title">
      <button type="button" class="datepicker-title-part datepicker-title-year">${e}\u5E74</button>
      <button type="button" class="datepicker-title-part datepicker-title-month">${t+1}\u6708</button>
    </span>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u6708">\u203A</button>
  `,n.querySelector(".datepicker-prev").addEventListener("click",o=>{o.stopPropagation(),setTimeout(s,0)}),n.querySelector(".datepicker-next").addEventListener("click",o=>{o.stopPropagation(),setTimeout(a,0)}),n.querySelector(".datepicker-title-year").addEventListener("click",o=>{o.stopPropagation(),setTimeout(()=>p("year"),0)}),n.querySelector(".datepicker-title-month").addEventListener("click",o=>{o.stopPropagation(),setTimeout(()=>p("month"),0)});let r=document.createElement("div");r.className="datepicker-weekdays",r.innerHTML=_.map(o=>`<span class="datepicker-weekday">${o}</span>`).join("");let i=document.createElement("div");return i.className="datepicker-days",j(e,t).forEach(({date:o,isCurrent:f,isToday:u})=>{let g=document.createElement("button");g.type="button",g.className="datepicker-day",f||g.classList.add("datepicker-day-other"),u&&g.classList.add("datepicker-day-today"),g.textContent=String(o.getDate()),g.addEventListener("click",C=>{C.stopPropagation(),l(o)}),i.appendChild(g)}),c.appendChild(n),c.appendChild(r),c.appendChild(i),c}function W(e,t,l,s,a){let p=document.createElement("div");p.className="datepicker-panel datepicker-month-panel";let c=document.createElement("div");c.className="datepicker-header",c.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u4E00\u5E74">\u2039</button>
    <button type="button" class="datepicker-panel-title">${e}\u5E74</button>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u4E00\u5E74">\u203A</button>
  `,c.querySelector(".datepicker-prev").addEventListener("click",r=>{r.stopPropagation(),setTimeout(l,0)}),c.querySelector(".datepicker-next").addEventListener("click",r=>{r.stopPropagation(),setTimeout(s,0)}),c.querySelector(".datepicker-panel-title").addEventListener("click",r=>{r.stopPropagation(),setTimeout(a,0)});let n=document.createElement("div");return n.className="datepicker-month-grid",$.forEach((r,i)=>{let d=document.createElement("button");d.type="button",d.className="datepicker-month-cell",d.textContent=r,d.addEventListener("click",o=>{o.stopPropagation(),setTimeout(()=>t(i),0)}),n.appendChild(d)}),p.appendChild(c),p.appendChild(n),p}function V(e,t,l,s){let a=document.createElement("div");a.className="datepicker-panel datepicker-year-panel";let p=document.createElement("div");p.className="datepicker-header";let c=e+b-1;p.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u9875">\u2039</button>
    <span class="datepicker-panel-title">${e} - ${c}</span>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u9875">\u203A</button>
  `,p.querySelector(".datepicker-prev").addEventListener("click",r=>{r.stopPropagation(),setTimeout(l,0)}),p.querySelector(".datepicker-next").addEventListener("click",r=>{r.stopPropagation(),setTimeout(s,0)});let n=document.createElement("div");n.className="datepicker-year-grid";for(let r=e;r<=c;r++){let i=document.createElement("button");i.type="button",i.className="datepicker-year-cell",i.textContent=String(r),i.addEventListener("click",d=>{d.stopPropagation(),setTimeout(()=>t(r),0)}),n.appendChild(i)}return a.appendChild(p),a.appendChild(n),a}function B(){z();let e=document.getElementById(x);return e||(e=document.createElement("div"),e.id=x,e.className="datepicker-overlay",document.body.appendChild(e)),e}var y=null,m=0,k=0,v=0,D=null;function h(e,t,l,s){let a=B(),c=(t!=null?typeof t=="string"?Y(t):t:new Date)||new Date;m=c.getFullYear(),k=c.getMonth(),v=Math.floor(m/b)*b,D=l||null,y=e instanceof HTMLInputElement?e:null;function n(d="calendar"){a.innerHTML="";let o=document.createElement("div");if(o.className="datepicker-box",d==="calendar"){let f=R(m,k,u=>{y&&y instanceof HTMLInputElement&&(y.value=A(u)),D?.(u),T()},()=>{k--,k<0&&(k=11,m--),n("calendar")},()=>{k++,k>11&&(k=0,m++),n("calendar")},u=>{n(u==="year"?"year":"month")});o.appendChild(f),a.appendChild(o);return}if(d==="month"){let f=W(m,u=>{k=u,n("calendar")},()=>{m--,n("month")},()=>{m++,n("month")},()=>n("year"));o.appendChild(f),a.appendChild(o);return}if(d==="year"){let f=V(v,u=>{m=u,n("month")},()=>{v-=b,n("year")},()=>{v+=b,n("year")});o.appendChild(f),a.appendChild(o)}}n("calendar"),a.classList.add("datepicker-visible");let r=(d=!1)=>{a.classList.remove("datepicker-visible"),document.removeEventListener("click",i),d&&s&&s()};function i(d){let o=d.target;if(!e.contains(o)){if(!a.contains(o)){r(!0);return}o===a&&r(!0)}}setTimeout(()=>document.addEventListener("click",i),0),a._close=r}function T(){let e=document.getElementById(x);e&&e._close&&e._close()}var w={bind(e){let t=typeof e=="string"?document.querySelector(e):e;if(!t)return()=>{};let l=()=>h(t,t.value);return t.addEventListener("focus",l),t.addEventListener("click",l),()=>{t.removeEventListener("focus",l),t.removeEventListener("click",l)}},open(e){h(e.anchor,e.value,e.onChange)},pick(e){let t=document.createElement("div");h(t,e?.value,e?.onChange)},pickAsync(e){return new Promise(t=>{let l=document.createElement("div");h(l,e?.value,s=>{T(),t(s)},()=>t(null))})},close:T};typeof window<"u"&&(window.datePicker=w);var O=w;0&&(module.exports={datePicker});
