"use strict";(()=>{var E="datepicker-wrapper",T="datepicker-injected-styles",C=["\u65E5","\u4E00","\u4E8C","\u4E09","\u56DB","\u4E94","\u516D"],M=`
.datepicker-overlay{position:fixed;inset:0;z-index:10003;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.45);opacity:0;visibility:hidden;transition:opacity .2s ease,visibility .2s ease}
.datepicker-overlay.datepicker-visible{opacity:1;visibility:visible}
.datepicker-box{margin:24px;padding:12px;background:#fff;border-radius:8px;box-shadow:0 6px 24px rgba(0,0,0,.15);border:1px solid #e8e8e8}
.datepicker-calendar{min-width:280px}
.datepicker-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}
.datepicker-title{display:flex;align-items:center;gap:2px;font-size:14px;font-weight:600;color:#333}
.datepicker-title-part{padding:4px 6px;border:none;background:transparent;border-radius:4px;font-size:inherit;font-weight:inherit;color:inherit;cursor:pointer}
.datepicker-title-part:hover{background:#e6f7ff;color:#1890ff}
.datepicker-panel{min-width:280px}
.datepicker-panel-title{padding:4px 8px;border:none;background:transparent;border-radius:4px;font-size:14px;font-weight:600;color:#333;cursor:pointer}
.datepicker-panel-title:hover{background:#e6f7ff;color:#1890ff}
.datepicker-month-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}
.datepicker-month-cell{padding:10px;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-month-cell:hover{background:#e6f7ff;color:#1890ff}
.datepicker-year-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}
.datepicker-year-cell{padding:10px;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-year-cell:hover{background:#e6f7ff;color:#1890ff}
.datepicker-nav{width:28px;height:28px;padding:0;border:none;background:transparent;border-radius:6px;font-size:18px;line-height:1;color:#666;cursor:pointer;display:flex;align-items:center;justify-content:center}
.datepicker-nav:hover{background:#f5f5f5;color:#333}
.datepicker-weekdays{display:grid;grid-template-columns:repeat(7,1fr);gap:2px;margin-bottom:8px}
.datepicker-weekday{text-align:center;font-size:12px;color:#999}
.datepicker-days{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}
.datepicker-day{width:36px;height:36px;padding:0;border:none;border-radius:6px;font-size:14px;background:transparent;color:#333;cursor:pointer}
.datepicker-day:hover{background:#e6f7ff;color:#1890ff}
.datepicker-day-other{color:#bfbfbf}
.datepicker-day-today{background:#e6f7ff;color:#1890ff;font-weight:600}
.datepicker-day.datepicker-day-today:hover{background:#bae7ff}
`;function P(){if(typeof document>"u"||document.getElementById(T))return;let e=document.createElement("style");e.id=T,e.textContent=M,document.head.appendChild(e)}var S=["1\u6708","2\u6708","3\u6708","4\u6708","5\u6708","6\u6708","7\u6708","8\u6708","9\u6708","10\u6708","11\u6708","12\u6708"],b=12;function N(e){let t=e.getFullYear(),l=String(e.getMonth()+1).padStart(2,"0"),p=String(e.getDate()).padStart(2,"0");return`${t}-${l}-${p}`}function H(e){if(!e)return null;let t=new Date(e);return isNaN(t.getTime())?null:t}function I(e,t){let l=new Date(e,t,1),p=new Date(e,t+1,0),c=l.getDay(),s=p.getDate(),d=[],n=new Date;n.setHours(0,0,0,0);for(let r=0;r<c;r++){let o=new Date(e,t,1-(c-r));d.push({date:o,isCurrent:!1,isToday:o.getTime()===n.getTime()})}for(let r=1;r<=s;r++){let o=new Date(e,t,r);d.push({date:o,isCurrent:!0,isToday:o.getTime()===n.getTime()})}let a=42-d.length;for(let r=1;r<=a;r++){let o=new Date(e,t+1,r);d.push({date:o,isCurrent:!1,isToday:o.getTime()===n.getTime()})}return d}function _(e,t,l,p,c,s){let d=document.createElement("div");d.className="datepicker-calendar";let n=document.createElement("div");n.className="datepicker-header",n.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u6708">\u2039</button>
    <span class="datepicker-title">
      <button type="button" class="datepicker-title-part datepicker-title-year">${e}\u5E74</button>
      <button type="button" class="datepicker-title-part datepicker-title-month">${t+1}\u6708</button>
    </span>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u6708">\u203A</button>
  `,n.querySelector(".datepicker-prev").addEventListener("click",i=>{i.stopPropagation(),setTimeout(p,0)}),n.querySelector(".datepicker-next").addEventListener("click",i=>{i.stopPropagation(),setTimeout(c,0)}),n.querySelector(".datepicker-title-year").addEventListener("click",i=>{i.stopPropagation(),setTimeout(()=>s("year"),0)}),n.querySelector(".datepicker-title-month").addEventListener("click",i=>{i.stopPropagation(),setTimeout(()=>s("month"),0)});let a=document.createElement("div");a.className="datepicker-weekdays",a.innerHTML=C.map(i=>`<span class="datepicker-weekday">${i}</span>`).join("");let r=document.createElement("div");return r.className="datepicker-days",I(e,t).forEach(({date:i,isCurrent:f,isToday:u})=>{let g=document.createElement("button");g.type="button",g.className="datepicker-day",f||g.classList.add("datepicker-day-other"),u&&g.classList.add("datepicker-day-today"),g.textContent=String(i.getDate()),g.addEventListener("click",D=>{D.stopPropagation(),l(i)}),r.appendChild(g)}),d.appendChild(n),d.appendChild(a),d.appendChild(r),d}function q(e,t,l,p,c){let s=document.createElement("div");s.className="datepicker-panel datepicker-month-panel";let d=document.createElement("div");d.className="datepicker-header",d.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u4E00\u5E74">\u2039</button>
    <button type="button" class="datepicker-panel-title">${e}\u5E74</button>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u4E00\u5E74">\u203A</button>
  `,d.querySelector(".datepicker-prev").addEventListener("click",a=>{a.stopPropagation(),setTimeout(l,0)}),d.querySelector(".datepicker-next").addEventListener("click",a=>{a.stopPropagation(),setTimeout(p,0)}),d.querySelector(".datepicker-panel-title").addEventListener("click",a=>{a.stopPropagation(),setTimeout(c,0)});let n=document.createElement("div");return n.className="datepicker-month-grid",S.forEach((a,r)=>{let o=document.createElement("button");o.type="button",o.className="datepicker-month-cell",o.textContent=a,o.addEventListener("click",i=>{i.stopPropagation(),setTimeout(()=>t(r),0)}),n.appendChild(o)}),s.appendChild(d),s.appendChild(n),s}function z(e,t,l,p){let c=document.createElement("div");c.className="datepicker-panel datepicker-year-panel";let s=document.createElement("div");s.className="datepicker-header";let d=e+b-1;s.innerHTML=`
    <button type="button" class="datepicker-nav datepicker-prev" aria-label="\u4E0A\u9875">\u2039</button>
    <span class="datepicker-panel-title">${e} - ${d}</span>
    <button type="button" class="datepicker-nav datepicker-next" aria-label="\u4E0B\u9875">\u203A</button>
  `,s.querySelector(".datepicker-prev").addEventListener("click",a=>{a.stopPropagation(),setTimeout(l,0)}),s.querySelector(".datepicker-next").addEventListener("click",a=>{a.stopPropagation(),setTimeout(p,0)});let n=document.createElement("div");n.className="datepicker-year-grid";for(let a=e;a<=d;a++){let r=document.createElement("button");r.type="button",r.className="datepicker-year-cell",r.textContent=String(a),r.addEventListener("click",o=>{o.stopPropagation(),setTimeout(()=>t(a),0)}),n.appendChild(r)}return c.appendChild(s),c.appendChild(n),c}function $(){P();let e=document.getElementById(E);return e||(e=document.createElement("div"),e.id=E,e.className="datepicker-overlay",document.body.appendChild(e)),e}var y=null,m=0,k=0,v=0,w=null;function h(e,t,l,p){let c=$(),d=(t!=null?typeof t=="string"?H(t):t:new Date)||new Date;m=d.getFullYear(),k=d.getMonth(),v=Math.floor(m/b)*b,w=l||null,y=e instanceof HTMLInputElement?e:null;function n(o="calendar"){c.innerHTML="";let i=document.createElement("div");if(i.className="datepicker-box",o==="calendar"){let f=_(m,k,u=>{y&&y instanceof HTMLInputElement&&(y.value=N(u)),w?.(u),x()},()=>{k--,k<0&&(k=11,m--),n("calendar")},()=>{k++,k>11&&(k=0,m++),n("calendar")},u=>{n(u==="year"?"year":"month")});i.appendChild(f),c.appendChild(i);return}if(o==="month"){let f=q(m,u=>{k=u,n("calendar")},()=>{m--,n("month")},()=>{m++,n("month")},()=>n("year"));i.appendChild(f),c.appendChild(i);return}if(o==="year"){let f=z(v,u=>{m=u,n("month")},()=>{v-=b,n("year")},()=>{v+=b,n("year")});i.appendChild(f),c.appendChild(i)}}n("calendar"),c.classList.add("datepicker-visible");let a=(o=!1)=>{c.classList.remove("datepicker-visible"),document.removeEventListener("click",r),o&&p&&p()};function r(o){let i=o.target;if(!e.contains(i)){if(!c.contains(i)){a(!0);return}i===c&&a(!0)}}setTimeout(()=>document.addEventListener("click",r),0),c._close=a}function x(){let e=document.getElementById(E);e&&e._close&&e._close()}var L={bind(e){let t=typeof e=="string"?document.querySelector(e):e;if(!t)return()=>{};let l=()=>h(t,t.value);return t.addEventListener("focus",l),t.addEventListener("click",l),()=>{t.removeEventListener("focus",l),t.removeEventListener("click",l)}},open(e){h(e.anchor,e.value,e.onChange)},pick(e){let t=document.createElement("div");h(t,e?.value,e?.onChange)},pickAsync(e){return new Promise(t=>{let l=document.createElement("div");h(l,e?.value,p=>{x(),t(p)},()=>t(null))})},close:x};typeof window<"u"&&(window.datePicker=L);var A=L;})();
